---
# tasks file for wdijkerman.zabbix-web

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: "Set short version name"
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"
  tags:
    - always

- name: "Install the correct repository"
  include: "Debian.yml"
  when: ansible_os_family == "Debian"
  tags:
    - zabbix-web

- name: "Create zabbix-web directory"
  file:
    path: /etc/zabbix/web
    group: "{{ www_group }}"
    state: directory
    mode: 0750
  tags:
    - zabbix-web
    - init
    - config

- name: "Configure zabbix-web"
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: 0640
  notify:
    - nginx restart
  tags:
    - zabbix-web
    - init
    - config

- name: "Configure zabbix-web in nginx"
  template:
    src: zabbix.site.j2
    dest: /etc/nginx/sites/zabbix.site
    mode: 0644
  notify:
    - nginx restart
  tags:
    - zabbix-web
    - init
    - config
