---
# handlers file for nginx
- name: zabbix web nginx reload
  become: yes
  service:
    name: nginx
    state: reloaded
  listen: nginx reload

- name: zabbix web nginx restart
  become: yes
  service:
    name: nginx
    state: restarted
  listen: nginx restart

